### ISSUE TITLE
How to use your module

### ISSUE THREAD

**Issue by vitormicillo** [fernandofauth/magento2_datetime#1]
Hi Fernando, 
what steps to use your module in magento 2.2.1

I just put the contents of the files in app / code and activated its module.
Then I executed the command
php bin / magento setup: upgrade

Do I need to do anything else?

**Comment by fernandofauth** [comment]
Hi Vitor.
I updated the instructions and tested on magento 2.2.1 .

**Comment by vitormicillo** [comment]
Thanks Fernando, 
You believe this modification works well with Magento 2.1.9 ?

**Comment by fernandofauth** [comment]
Looking at the 2.1.9 file I believe yes.

**Comment by vitormicillo** [comment]
Beleza obrigado..
